org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.219
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=regrownoffline
mod_name=Regrown Offline
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.regrownoffline
mod_authors=misterjosephbear
mod_description=Player-built structures visually decay and revert to their natural state when the area has been offline for extended periods.
