package com.regrownoffline.worldgen;

import com.regrownoffline.RegrownOffline;
import com.regrownoffline.data.ChunkDecayData;
import net.minecraft.Util;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.WorldGenRegion;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.chunk.LevelChunkSection;
import net.minecraft.world.level.chunk.ProtoChunk;
import net.minecraft.world.level.chunk.UpgradeData;
import net.minecraft.world.level.chunk.LevelChunk;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import net.minecraft.world.level.levelgen.RandomState;
import net.minecraft.world.level.levelgen.blending.Blender;
// TODO: this import is a placeholder - IntelliJ couldn't find StructureManager here either.
// Put your cursor on "StructureManager" below (e.g. on the "level.structureManager()" line) and
// press Alt+Enter -> "Import class" to let the IDE find the real package, then delete this line.

import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * Regenerates a chunk's "natural" baseline in memory using the level's {@link ChunkGenerator} and
 * {@link RandomState}, then diffs it against the live chunk to seed {@link ChunkDecayData}.
 *
 * <h2>Scope of the baseline</h2>
 * The baseline reproduces terrain shape (biomes + density-function noise, i.e. stone/deepslate/water/
 * air) and the biome surface layer (grass/dirt/sand/etc. via surface rules) only. Carvers
 * (caves/ravines), decorator features (trees, ore veins, vegetation) and structures are deliberately
 * <b>not</b> replayed: those generation steps read and write neighboring chunks, and reproducing them
 * deterministically for a single isolated chunk would mean reimplementing large parts of vanilla's
 * multi-chunk "generation pyramid" (the same reason a chunk needs ~11 chunks of neighbor context to
 * reach {@code ChunkStatus.FULL}). Practical consequence: a player-dug cave will not be filled back
 * in, and a village generated by worldgen is not treated as a player build. Anything a player places
 * on top of raw terrain/surface — the overwhelming majority of what this mod cares about — is still
 * diffed correctly.
 *
 * <h2>Threading</h2>
 * The expensive generation steps ({@link #buildBaselineChunk}) run on {@link Util#backgroundExecutor()},
 * mirroring how vanilla itself runs these same {@link ChunkGenerator} steps off the main thread as part
 * of normal chunk loading. The diff against the live chunk and every mutation of {@link ChunkDecayData}
 * happens back on the server thread via {@code level.getServer()} for thread safety.
 *
 * <h2>Build risk</h2>
 * This file calls internal {@code ChunkGenerator}/{@code ChunkStatus} generation-step methods, some of
 * the most version-volatile APIs in the codebase. It was written from API knowledge without a compiler
 * available in the authoring sandbox (outbound access to {@code maven.neoforged.net} was blocked, so no
 * NeoForge/Minecraft jars could be fetched to verify exact signatures). <b>Run {@code ./gradlew
 * compileJava} and fix any signature mismatches here first</b> — cross-reference against
 * {@code net.minecraft.world.level.chunk.status.ChunkStatus} and {@code ChunkGenerator} in the
 * NeoForge/MC 1.21.1 sources (e.g. via a decompiled sources jar or your IDE's "go to definition") before
 * relying on this in a real world.
 */
public final class BaselineGenerator {

    private BaselineGenerator() {
    }

    /** Kicks off async baseline generation + diff for {@code liveChunk}. No-op if already generated. */
    public static void generateAndDiff(ServerLevel level, LevelChunk liveChunk) {
        ChunkPos pos = liveChunk.getPos();
        ChunkDecayData data = ChunkDecayData.get(level);
        ChunkDecayData.ChunkRecord record = data.getOrCreateRecord(pos);
        if (record.isBaselineGenerated()) {
            return;
        }

        ChunkGenerator generator = level.getChunkSource().getGenerator();
        RandomState randomState = level.getChunkSource().randomState();
        StructureManager structureManager = level.structureManager();
        Registry<Biome> biomes = level.registryAccess().registryOrThrow(Registries.BIOME);

        CompletableFuture
                .supplyAsync(() -> buildBaselineChunk(level, generator, randomState, structureManager, biomes, pos),
                        Util.backgroundExecutor())
                .whenCompleteAsync((baseline, throwable) -> {
                    if (throwable != null) {
                        RegrownOffline.LOGGER.error("Failed to build decay baseline for chunk {}", pos, throwable);
                        return;
                    }
                    applyBaseline(level, liveChunk, baseline);
                }, level.getServer());
    }

    private static ChunkAccess buildBaselineChunk(ServerLevel level, ChunkGenerator generator, RandomState randomState,
                                                    StructureManager structureManager, Registry<Biome> biomes, ChunkPos pos) {
        ProtoChunk protoChunk = new ProtoChunk(pos, UpgradeData.EMPTY, level, biomes, null);
        List<ChunkAccess> soloRegion = List.of(protoChunk);

        // Executor::run makes these steps execute synchronously on this (already background) thread.
        generator.createBiomes(Runnable::run, randomState, Blender.empty(), structureManager, protoChunk).join();
        generator.fillFromNoise(Runnable::run, Blender.empty(), randomState, structureManager, protoChunk).join();

        // A single-chunk WorldGenRegion is sufficient for buildSurface, which only reads the chunk's
        // own noise column/biome data - deliberately not calling applyCarvers/applyBiomeDecoration here,
        // see the "Scope of the baseline" note above.
        WorldGenRegion region = new WorldGenRegion(level, soloRegion, ChunkStatus.SURFACE, 0);
        generator.buildSurface(region, structureManager, randomState, protoChunk);

        return protoChunk;
    }

    private static void applyBaseline(ServerLevel level, LevelChunk liveChunk, ChunkAccess baseline) {
        ChunkPos pos = liveChunk.getPos();
        ChunkDecayData data = ChunkDecayData.get(level);
        ChunkDecayData.ChunkRecord record = data.getOrCreateRecord(pos);
        if (record.isBaselineGenerated()) {
            return; // lost a race with another trigger for the same chunk; first result wins
        }

        BaselineCache.put(level, pos, baseline);

        long now = System.currentTimeMillis();
        BlockPos.MutableBlockPos cursor = new BlockPos.MutableBlockPos();
        int sectionCount = liveChunk.getSectionsCount();

        for (int sectionIndex = 0; sectionIndex < sectionCount; sectionIndex++) {
            LevelChunkSection liveSection = liveChunk.getSection(sectionIndex);
            LevelChunkSection baselineSection = baseline.getSection(sectionIndex);
            if (liveSection.hasOnlyAir() && baselineSection.hasOnlyAir()) {
                continue; // cheap skip for the (usually large) all-air portions of the column
            }

            int sectionMinY = liveChunk.getSectionYFromSectionIndex(sectionIndex) << 4;
            for (int dy = 0; dy < 16; dy++) {
                int y = sectionMinY + dy;
                for (int x = 0; x < 16; x++) {
                    for (int z = 0; z < 16; z++) {
                        cursor.set(pos.getMinBlockX() + x, y, pos.getMinBlockZ() + z);
                        BlockState liveState = liveChunk.getBlockState(cursor);
                        BlockState baselineState = baseline.getBlockState(cursor);
                        if (!liveState.equals(baselineState)) {
                            // Timestamped "now" so pre-existing (retroactive) diffs count their offline
                            // clock from mod install / first-load time rather than from placement time.
                            record.diffs().put(cursor.immutable(), new ChunkDecayData.TrackedDiff(liveState, baselineState, now));
                        }
                    }
                }
            }
        }

        record.markBaselineGenerated();
        record.touch(now, null);
        data.setDirty();

        RegrownOffline.LOGGER.debug("Baseline ready for chunk {}: {} diffed block(s)", pos, record.diffs().size());
    }
}
